# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink: pretty

# Setup
title: sweetnsharp
tagline: 'blog'
description:'My personal blog.'
url:	http://lynsharp.github.io

author:
  name:	'lyn'
  url: https://google.com/+

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg
